#ifndef NUKLEAR_RUST_WRAPPER_H
#define NUKLEAR_RUST_WRAPPER_H

#define NK_IMPLEMENTATION
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_COMMAND_USERDATA
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING

#include "nuklear-c/nuklear/nuklear.h"

#endif //NUKLEAR_RUST_WRAPPER_H
